FROM ubuntu:16.04

LABEL description="HamroAudit"
LABEL version="0.1"
LABEL vendor="HamroAudit"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

WORKDIR /hamro-audit
COPY . /hamro-audit

#JVM Related Like Heap, Garbage Collector
ENV JAVA_OPTS "-Xms4G -Xmx4G"
ENV APP_ARGS "-Dlogback.configurationFile=/some/path/logback.xml -Dservice.config.file=/some/path/service.properties"
EXPOSE 9090
RUN ./gradlew distTar && tar -xzf build/distributions/hamro-audit-1.0-SNAPSHOT.tar
CMD hamro-audit-1.0-SNAPSHOT/bin/hamro-audit $APP_ARGS