spring:
  application:
    name: hamro-audit

  data:
    mongodb:
      database: hamro-audit
      uri: mongodb://mongodb:27017/
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:29092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsUserChanged:
          destination: moments.user.changed
          contentType: application/json
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      bootstrap-servers: kafka:29092
    producer:
      bootstrap-servers: kafka:29092

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

hamroaudit:
  aws:
    access_key_id: AKIA2P2YZ57L6XF7JRPE
    secret_access_key: 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
  s3:
    bucket: hamro-audit-file
    region: us-east-1
    uploadfile: ./assets/


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33